In [3]:
import numpy as np
import scipy.io

In [4]:
meta = scipy.io.loadmat('data/meta.mat')

In [5]:
meta.shape

AttributeError: 'dict' object has no attribute 'shape'

In [7]:
meta['synsets'].shape

(1860, 1)

In [8]:
meta.keys()

dict_keys(['__header__', '__version__', '__globals__', 'synsets'])

In [11]:
meta['synsets'][0]

array([ (array([[1]], dtype=uint8), array(['n02119789'],
      dtype='<U9'), array(['kit fox, Vulpes macrotis'],
      dtype='<U24'), array([ 'small grey fox of southwestern United States; may be a subspecies of Vulpes velox'],
      dtype='<U81'), array([[0]], dtype=uint8), array([], shape=(1, 0), dtype=uint8), array([[0]], dtype=uint8), array([[1300]], dtype=uint16))],
      dtype=[('ILSVRC2012_ID', 'O'), ('WNID', 'O'), ('words', 'O'), ('gloss', 'O'), ('num_children', 'O'), ('children', 'O'), ('wordnet_height', 'O'), ('num_train_images', 'O')])

In [12]:
meta["synsets"][0,0]

(array([[1]], dtype=uint8), array(['n02119789'],
      dtype='<U9'), array(['kit fox, Vulpes macrotis'],
      dtype='<U24'), array([ 'small grey fox of southwestern United States; may be a subspecies of Vulpes velox'],
      dtype='<U81'), array([[0]], dtype=uint8), array([], shape=(1, 0), dtype=uint8), array([[0]], dtype=uint8), array([[1300]], dtype=uint16))

In [13]:
meta["synsets"][0][0]

(array([[1]], dtype=uint8), array(['n02119789'],
      dtype='<U9'), array(['kit fox, Vulpes macrotis'],
      dtype='<U24'), array([ 'small grey fox of southwestern United States; may be a subspecies of Vulpes velox'],
      dtype='<U81'), array([[0]], dtype=uint8), array([], shape=(1, 0), dtype=uint8), array([[0]], dtype=uint8), array([[1300]], dtype=uint16))

In [14]:
meta["synsets"][0][0][0]

array([[1]], dtype=uint8)

In [15]:
meta["synsets"][0,0][0]

array([[1]], dtype=uint8)

In [17]:
meta["synsets"][0][0][0][0]

array([1], dtype=uint8)

In [18]:
meta["synsets"][0][0][0][0][0]

1

In [19]:
meta["synsets"][0][0][1]

array(['n02119789'],
      dtype='<U9')

In [20]:
meta["synsets"][0][0][1][0]

'n02119789'

In [21]:
meta['synsets'][5]

array([ (array([[6]], dtype=uint8), array(['n02066245'],
      dtype='<U9'), array([ 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus'],
      dtype='<U79'), array(['medium-sized greyish-black whale of the northern Pacific'],
      dtype='<U56'), array([[0]], dtype=uint8), array([], shape=(1, 0), dtype=uint8), array([[0]], dtype=uint8), array([[1150]], dtype=uint16))],
      dtype=[('ILSVRC2012_ID', 'O'), ('WNID', 'O'), ('words', 'O'), ('gloss', 'O'), ('num_children', 'O'), ('children', 'O'), ('wordnet_height', 'O'), ('num_train_images', 'O')])